import type { Instructor } from "./Instructor.type";

export const instructorDummyData: Instructor[] = [
    {
        id: 1,
        name: "John Smith",
        image: '/assets/img/instructor.png',
        email: "john.smith@example.com",
        work_as: "Assistant Professor",
        department: "Computer Science",
        rating: {
            total_rating: 100,
            total_vote: 50,
            rating: 4,
            ratings: {
                helpful: 2,
                easiness: 4,
                clarity: 4,
            },
        },
    },
    {
        id: 2,
        name: "Alice Johnson",
        image: '/assets/img/instructor.png',
        email: "alice.johnson@example.com",
        work_as: "Lecturer",
        department: "Mathematics",
        rating: {
            total_rating: 80,
            total_vote: 40,
            rating: 4,
            ratings: {
                helpful: 4,
                easiness: 4,
                clarity: 4,
            },
        },
    },
    {
        id: 3,
        name: "David Brown",
        image: '/assets/img/instructor-2.png',
        email: "david.brown@example.com",
        work_as: "Associate Professor",
        department: "Physics",
        rating: {
            total_rating: 120,
            total_vote: 60,
            rating: 4,
            ratings: {
                helpful: 4,
                easiness: 4,
                clarity: 4,
            },
        },
    },
    {
        id: 4,
        name: "Emily Davis",
        image: '/assets/img/instructor.png',
        email: "emily.davis@example.com",
        work_as: "Professor",
        department: "Chemistry",
        rating: {
            total_rating: 90,
            total_vote: 45,
            rating: 4,
            ratings: {
                helpful: 4,
                easiness: 4,
                clarity: 4,
            },
        },
    },
    {
        id: 2,
        name: "Michael Wilson",
        image: '/assets/img/instructor-2.png',
        email: "michael.wilson@example.com",
        work_as: "Assistant Professor",
        department: "Biology",
        rating: {
            total_rating: 75,
            total_vote: 35,
            rating: 4,
            ratings: {
                helpful: 3.9,
                easiness: 4,
                clarity: 3.8,
            },
        },
    },
    {
        id: 2,
        name: "Sarah Thompson",
        image: '/assets/img/instructor.png',
        email: "sarah.thompson@example.com",
        work_as: "Lecturer",
        department: "History",
        rating: {
            total_rating: 110,
            total_vote: 55,
            rating: 4,
            ratings: {
                helpful: 4,
                easiness: 4,
                clarity: 4,
            },
        },
    },
    {
        id: 2,
        name: "Daniel Johnson",
        image: '/assets/img/instructor-2.png',
        email: "daniel.johnson@example.com",
        work_as: "Associate Professor",
        department: "Economics",
        rating: {
            total_rating: 95,
            total_vote: 50,
            rating: 4,
            ratings: {
                helpful: 4,
                easiness: 4,
                clarity: 4,
            },
        },
    },
    {
        id: 2,
        name: "Olivia Davis",
        image: '/assets/img/instructor.png',
        email: "olivia.davis@example.com",
        work_as: "Professor",
        department: "English",
        rating: {
            total_rating: 85,
            total_vote: 40,
            rating: 4,
            ratings: {
                helpful: 4,
                easiness: 4,
                clarity: 4,
            },
        },
    },
    {
        id: 2,
        name: "Christopher Wilson",
        image: '/assets/img/instructor.png',
        email: "christopher.wilson@example.com",
        work_as: "Assistant Professor",
        department: "Psychology",
        rating: {
            total_rating: 105,
            total_vote: 55,
            rating: 4,
            ratings: {
                helpful: 4,
                easiness: 4,
                clarity: 4,
            },
        },
    },
    {
        id: 2,
        name: "Sophia Thompson",
        image: '/assets/img/instructor.png',
        email: "sophia.thompson@example.com",
        work_as: "Lecturer",
        department: "Sociology",
        rating: {
            total_rating: 115,
            total_vote: 60,
            rating: 4,
            ratings: {
                helpful: 4,
                easiness: 4,
                clarity: 4,
            },
        },
    },
    {
        id: 2,
        name: "Matthew Davis",
        image: '/assets/img/instructor.png',
        email: "matthew.davis@example.com",
        work_as: "Associate Professor",
        department: "Political Science",
        rating: {
            total_rating: 100,
            total_vote: 50,
            rating: 4,
            ratings: {
                helpful: 4,
                easiness: 4,
                clarity: 4,
            },
        },
    },
    {
        id: 2,
        name: "Emma Johnson",
        image: '/assets/img/instructor.png',
        email: "emma.johnson@example.com",
        work_as: "Professor",
        department: "Art",
        rating: {
            total_rating: 80,
            total_vote: 40,
            rating: 4,
            ratings: {
                helpful: 4,
                easiness: 4,
                clarity: 4,
            },
        },
    },
    {
        id: 2,
        name: "James Brown",
        image: '/assets/img/instructor.png',
        email: "james.brown@example.com",
        work_as: "Assistant Professor",
        department: "Music",
        rating: {
            total_rating: 120,
            total_vote: 60,
            rating: 4,
            ratings: {
                helpful: 4,
                easiness: 4,
                clarity: 4,
            },
        },
    },
    {
        id: 2,
        name: "Ava Wilson",
        image: '/assets/img/instructor.png',
        email: "ava.wilson@example.com",
        work_as: "Lecturer",
        department: "Theater",
        rating: {
            total_rating: 90,
            total_vote: 45,
            rating: 4,
            ratings: {
                helpful: 4,
                easiness: 4,
                clarity: 4,
            },
        },
    },
    {
        id: 2,
        name: "Logan Thompson",
        image: '/assets/img/instructor.png',
        email: "logan.thompson@example.com",
        work_as: "Associate Professor",
        department: "Film Studies",
        rating: {
            total_rating: 75,
            total_vote: 35,
            rating: 4,
            ratings: {
                helpful: 3.9,
                easiness: 4,
                clarity: 3.8,
            },
        },
    },
    {
        id: 2,
        name: "Mia Davis",
        image: '/assets/img/instructor.png',
        email: "mia.davis@example.com",
        work_as: "Professor",
        department: "Dance",
        rating: {
            total_rating: 110,
            total_vote: 55,
            rating: 4,
            ratings: {
                helpful: 4,
                easiness: 4,
                clarity: 4,
            },
        },
    },
    {
        id: 2,
        name: "Benjamin Johnson",
        image: '/assets/img/instructor.png',
        email: "benjamin.johnson@example.com",
        work_as: "Assistant Professor",
        department: "Architecture",
        rating: {
            total_rating: 95,
            total_vote: 50,
            rating: 4,
            ratings: {
                helpful: 4,
                easiness: 4,
                clarity: 4,
            },
        },
    },
    {
        id: 2,
        name: "Abigail Davis",
        image: '/assets/img/instructor.png',
        email: "abigail.davis@example.com",
        work_as: "Lecturer",
        department: "Environmental Science",
        rating: {
            total_rating: 85,
            total_vote: 40,
            rating: 4,
            ratings: {
                helpful: 4,
                easiness: 4,
                clarity: 4,
            },
        },
    },
    {
        id: 2,
        name: "Daniel Wilson",
        image: '/assets/img/instructor.png',
        email: "daniel.wilson@example.com",
        work_as: "Associate Professor",
        department: "Geology",
        rating: {
            total_rating: 105,
            total_vote: 55,
            rating: 4,
            ratings: {
                helpful: 4,
                easiness: 4,
                clarity: 4,
            },
        },
    },
    {
        id: 2,
        name: "Ella Thompson",
        image: '/assets/img/instructor.png',
        email: "ella.thompson@example.com",
        work_as: "Professor",
        department: "Anthropology",
        rating: {
            total_rating: 115,
            total_vote: 60,
            rating: 4,
            ratings: {
                helpful: 4,
                easiness: 4,
                clarity: 4,
            },
        },
    },
    {
        id: 2,
        name: "Jack Davis",
        image: '/assets/img/instructor.png',
        email: "jack.davis@example.com",
        work_as: "Assistant Professor",
        department: "Foreign Languages",
        rating: {
            total_rating: 100,
            total_vote: 50,
            rating: 4,
            ratings: {
                helpful: 4,
                easiness: 4,
                clarity: 4,
            },
        },
    },
    {
        id: 2,
        name: "Sofia Johnson",
        image: '/assets/img/instructor.png',
        email: "sofia.johnson@example.com",
        work_as: "Lecturer",
        department: "Philosophy",
        rating: {
            total_rating: 80,
            total_vote: 40,
            rating: 4,
            ratings: {
                helpful: 4,
                easiness: 4,
                clarity: 3.1
            }
        }
    }]