export interface IGuest {
    id: string;
    name: string;
    email: string;
    progress: number;
    percentage: number;
    passFail: 'pass' | 'fail' | 'none';
    attendance: number;
    days: string[];
    image: string;
}


export const guestProgressDataMock = [
    {
        id: "1",
        code: 'S2001',
        name: 'Ava Baker',
        course: 1,
        recruited: 50,
        image: "/assets/img/avatar/avatar-1.jpeg"
    },
    {
        id: "2",
        code: 'S2002',
        name: 'David Burn',
        course: 1,
        recruited: 40,
        image: "/assets/img/avatar/avatar-2.jpeg"
    },
    {
        id: "3",
        code: 'S2003',
        name: 'Fiona Green',
        course: 1,
        recruited: 80,
        image: "/assets/img/avatar/avatar-3.jpeg"
    },
    {
        id: "4",
        code: 'S2004',
        name: 'Gabriel Hayes',
        course: 1,
        recruited: 60,
        image: "/assets/img/avatar/avatar-3.jpeg"
    },
    {
        id: "5",
        code: 'S2005',
        name: 'Jacob John',
        course: 1,
        recruited: 70,
        image: "/assets/img/avatar/avatar-3.jpeg"
    },
    {
        id: "6",
        code: 'S2006',
        name: 'Liam Mitchell ',
        course: 1,
        recruited: 40,
        image: "/assets/img/avatar/avatar-3.jpeg"
    },
    {
        id: "4",
        code: 'S2004',
        name: 'Gabriel Hayes',
        course: 1,
        recruited: 70,
        image: "/assets/img/avatar/avatar-4.jpeg"
    },
    {
        id: "5",
        code: 'S2005',
        name: 'Jacob John',
        course: 1,
        recruited: 60,
        image: "/assets/img/avatar/avatar-5.jpeg"
    },
    {
        id: "6",
        code: 'S2004',
        name: 'Kevin Duran',
        course: 1,
        recruited: 30,
        image: "/assets/img/avatar/avatar-6.jpeg"
    },
];

export const guestListDataMock: IGuest[] = [
    {
        id: '1',
        name: 'Guest 1',
        image: '',
        email: 'guest1@gmail.com',
        progress: 50,
        percentage: 80,
        passFail: 'pass',
        attendance: 5,
        days: [
            'passed',
            'passed',
            'passed',
            'passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
        ],
    },
    {
        id: '2',
        name: 'Guest 2',
        image: '',
        email: 'guest2@gmail.com',
        progress: 50,
        percentage: 80,
        passFail: 'pass',
        attendance: 5,
        days: [
            'passed',
            'passed',
            'passed',
            'passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
        ],
    },
    {
        id: '3',
        name: 'Guest 3',
        image: '',
        email: 'guest3@gmail.com',
        progress: 50,
        percentage: 80,
        passFail: 'fail',
        attendance: 5,
        days: [
            'passed',
            'passed',
            'passed',
            'passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
        ],
    },
    {
        id: '4',
        name: 'Guest 4',
        image: '',
        email: 'guest4@gmail.com',
        progress: 80,
        percentage: 80,
        passFail: 'none',
        attendance: 5,
        days: [
            'passed',
            'passed',
            'passed',
            'passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
        ],
    },
    {
        id: '5',
        name: 'Guest 5',
        image: '',
        email: 'guest5@gmail.com',
        progress: 80,
        percentage: 80,
        passFail: 'pass',
        attendance: 5,
        days: [
            'passed',
            'passed',
            'passed',
            'passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
        ],
    },
    {
        id: '6',
        name: 'Guest 6',
        image: '',
        email: 'guest6@gmail.com',
        progress: 60,
        percentage: 80,
        passFail: 'pass',
        attendance: 5,
        days: [
            'passed',
            'passed',
            'passed',
            'passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
        ],
    },
    {
        id: '7',
        name: 'Guest 7',
        image: '',
        email: 'guest7@gmail.com',
        progress: 70,
        percentage: 80,
        passFail: 'pass',
        attendance: 5,
        days: [
            'passed',
            'passed',
            'passed',
            'passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
        ],
    },
    {
        id: '8',
        name: 'Guest 8',
        image: '',
        email: 'guest8@gmail.com',
        progress: 70,
        percentage: 80,
        passFail: 'pass',
        attendance: 5,
        days: [
            'passed',
            'passed',
            'passed',
            'passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
        ],
    },
    {
        id: '9',
        name: 'Guest 9',
        image: '',
        email: 'guest9@gmail.com',
        progress: 70,
        percentage: 80,
        passFail: 'pass',
        attendance: 5,
        days: [
            'passed',
            'passed',
            'passed',
            'passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
        ],
    },
    {
        id: '10',
        name: 'Guest 10',
        image: '',
        email: 'guest10@gmail.com',
        progress: 90,
        percentage: 80,
        passFail: 'pass',
        attendance: 5,
        days: [
            'passed',
            'passed',
            'passed',
            'passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
        ],
    },
    {
        id: '11',
        name: 'Guest 11',
        image: '',
        email: 'guest11@gmail.com',
        progress: 50,
        percentage: 80,
        passFail: 'pass',
        attendance: 5,
        days: [
            'passed',
            'passed',
            'passed',
            'passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
        ],
    },
    {
        id: '12',
        name: 'Guest 12',
        image: '',
        email: 'guest12@gmail.com',
        progress: 50,
        percentage: 80,
        passFail: 'pass',
        attendance: 5,
        days: [
            'passed',
            'passed',
            'passed',
            'passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
        ],
    },
    {
        id: '13',
        name: 'Guest 13',
        image: '',
        email: 'guest13@gmail.com',
        progress: 50,
        percentage: 80,
        passFail: 'pass',
        attendance: 5,
        days: [
            'passed',
            'passed',
            'passed',
            'passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
        ],
    },
    {
        id: '14',
        name: 'Guest 14',
        image: '',
        email: 'guest14@gmail.com',
        progress: 50,
        percentage: 80,
        passFail: 'pass',
        attendance: 5,
        days: [
            'passed',
            'passed',
            'passed',
            'passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
        ],
    },
    {
        id: '15',
        name: 'Guest 15',
        image: '',
        email: 'guest15@gmail.com',
        progress: 50,
        percentage: 80,
        passFail: 'pass',
        attendance: 5,
        days: [
            'passed',
            'passed',
            'passed',
            'passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
        ],
    },
    {
        id: '16',
        name: 'Guest 16',
        image: '',
        email: 'guest16@gmail.com',
        progress: 50,
        percentage: 80,
        passFail: 'pass',
        attendance: 5,
        days: [
            'passed',
            'passed',
            'passed',
            'passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
        ],
    },
    {
        id: '17',
        name: 'Guest 17',
        image: '',
        email: 'guest17@gmail.com',
        progress: 50,
        percentage: 80,
        passFail: 'pass',
        attendance: 5,
        days: [
            'passed',
            'passed',
            'passed',
            'passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
            'not passed',
        ],
    },

]