import type { IGuest } from "./GuestProgressDetail.type"

export const guestListData: IGuest[] = [
    {
        id: '1',
        name: 'Guest 1',
        email: 'email@gmail.com',
        progress: 100,
        percentage: '100%',
        passFail: 'Passed',
        attendance: 5,
        days: [
          'passed',
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '2',
        name: 'Guest 2',
        email: 'email@gmail.com',
        progress: 100,
        percentage: '100%',
        passFail: 'Passed',
        attendance: 9,
        days: [
          'passed',
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '3',
        name: 'Guest 3',
        email: 'email@gmail.com',
        progress: 100,
        percentage: '100%',
        passFail: 'Passed',
        attendance: 7,
        days: [
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '4',
        name: 'Guest 4',
        email: 'email@gmail.com',
        progress: 100,
        percentage: '100%',
        passFail: 'Passed',
        attendance: 8,
        days: [
          'passed',
          'passed',
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '5',
        name: 'Guest 5',
        email: 'email@gmail.com',
        progress: 100,
        percentage: '100%',
        passFail: 'Failed',
        attendance: 3,
        days: [
          'passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '6',
        name: 'Guest 6',
        email: 'email@gmail.com',
        progress: 100,
        percentage: '100%',
        passFail: 'Passed',
        attendance: 6,
        days: [
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '7',
        name: 'Guest 7',
        email: 'email@gmail.com',
        progress: 100,
        percentage: '100%',
        passFail: 'Failed',
        attendance: 4,
        days: [
          'passed',
          'passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '8',
        name: 'Guest 8',
        email: 'email@gmail.com',
        progress: 100,
        percentage: '100%',
        passFail: 'Passed',
        attendance: 9,
        days: [
          'passed',
          'passed',
          'passed',
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '9',
        name: 'Guest 9',
        email: 'email@gmail.com',
        progress: 100,
        percentage: '100%',
        passFail: 'Passed',
        attendance: 7,
        days: [
          'passed',
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '10',
        name: 'Guest 10',
        email: 'email@gmail.com',
        progress: 100,
        percentage: '100%',
        passFail: 'Passed',
        attendance: 8,
        days: [
          'passed',
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '11',
        name: 'Guest 11',
        email: 'email@gmail.com',
        progress: 100,
        percentage: '100%',
        passFail: 'Passed',
        attendance: 5,
        days: [
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '12',
        name: 'Guest 12',
        email: 'email@gmail.com',
        progress: 100,
        percentage: '100%',
        passFail: 'Passed',
        attendance: 9,
        days: [
          'passed',
          'passed',
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '13',
        name: 'Guest 13',
        email: 'email@gmail.com',
        progress: 100,
        percentage: '100%',
        passFail: 'Failed',
        attendance: 4,
        days: [
          'passed',
          'passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '14',
        name: 'Guest 14',
        email: 'email@gmail.com',
        progress: 100,
        percentage: '100%',
        passFail: 'Passed',
        attendance: 8,
        days: [
          'passed',
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '15',
        name: 'Guest 15',
        email: 'email@gmail.com',
        progress: 100,
        percentage: '100%',
        passFail: 'Passed',
        attendance: 7,
        days: [
          'passed',
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '16',
        name: 'Guest 16',
        email: 'email@gmail.com',
        progress: 100,
        percentage: '100%',
        passFail: 'Passed',
        attendance: 6,
        days: [
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '17',
        name: 'Guest 17',
        email: 'email@gmail.com',
        progress: 100,
        percentage: '100%',
        passFail: 'Failed',
        attendance: 3,
        days: [
          'passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '18',
        name: 'Guest 18',
        email: 'email@gmail.com',
        progress: 100,
        percentage: '100%',
        passFail: 'Passed',
        attendance: 9,
        days: [
          'passed',
          'passed',
          'passed',
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '19',
        name: 'Guest 19',
        email: 'email@gmail.com',
        progress: 100,
        percentage: '100%',
        passFail: 'Passed',
        attendance: 7,
        days: [
          'passed',
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '20',
        name: 'Guest 20',
        email: 'email@gmail.com',
        progress: 100,
        percentage: '100%',
        passFail: 'Passed',
        attendance: 8,
        days: [
          'passed',
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
          'not passed',
        ],
      }
      
      
]