import type { IStudent } from "./StudentProgressDetail.type";

export const studentData: IStudent[] = [
    {
        id: '1',
        name: 'John Tason',
        email: 'JohnToson@gmail.com',
        progress: 100,
        percentage: '100%',
        passFail: 'Passed',
        attendance: 5,
        image: '/assets/img/student/student.png',
        days: [
          'passed',
          'passed',
          'not passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '2',
        name: 'Isabel Tray',
        email: 'IsabelT@gmail.com',
        progress: 100,
        percentage: '100%',
        passFail: 'Passed',
        attendance: 5,
        image: '/assets/img/instructor.png',
        days: [
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '3',
        name: 'Ken Troy',
        email: 'KenTroy@gmail.com',
        progress: 100,
        percentage: '100%',
        passFail: 'Passed',
        attendance: 5,
        image: '/assets/img/instructor.png',
        days: [
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '4',
        name: 'Rachel May',
        email: 'RachelMay@gmail.com',
        progress: 100,
        percentage: '50%',
        passFail: 'Failed',
        attendance: 5,
        image: '/assets/img/instructor.png',
        days: [
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '4',
        name: 'Kenny Mathew',
        email: 'KenMatt@gmail.com',
        progress: 90,
        percentage: '90%',
        passFail: 'Non',
        attendance: 5,
        image: '/assets/img/instructor.png',
        days: [
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '5',
        name: 'Charles Young',
        email: 'CharlesYoung@gmail.com',
        progress: 90,
        percentage: '70%',
        passFail: 'Non',
        attendance: 5,
        image: '/assets/img/instructor.png',
        days: [
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '6',
        name: 'Zac Jordan',
        email: 'ZJordan@gmail.com',
        progress: 80,
        percentage: '70%',
        passFail: 'Non',
        attendance: 5,
        image: '/assets/img/instructor.png',
        days: [
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '7',
        name: 'Melody Hannah',
        email: 'MelodyH@gmail.com',
        progress: 80,
        percentage: '75%',
        passFail: 'Non',
        attendance: 5,
        image: '/assets/img/instructor.png',
        days: [
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '7',
        name: 'Rachel Lorey',
        email: 'RachelLorey@gmail.com',
        progress: 70,
        percentage: '70%',
        passFail: 'Non',
        attendance: 5,
        image: '/assets/img/instructor.png',
        days: [
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '7',
        name: 'Jennifer Pan',
        email: 'JenPan@gmail.com',
        progress: 50,
        percentage: '50%',
        passFail: 'Non',
        attendance: 5,
        image: '/assets/img/instructor.png',
        days: [
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '8',
        name: 'Alex Smith',
        email: 'AlexSmith@gmail.com',
        progress: 95,
        percentage: '95%',
        passFail: 'Non',
        attendance: 5,
        image: '/assets/img/instructor.png',
        days: [
          'passed',
          'passed',
          'passed',
          'passed',
          'not passed',
        ],
      },
      {
        id: '9',
        name: 'Emily Brown',
        email: 'EmilyBrown@gmail.com',
        progress: 85,
        percentage: '85%',
        passFail: 'Non',
        attendance: 5,
        image: '/assets/img/instructor.png',
        days: [
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '10',
        name: 'Liam Johnson',
        email: 'LiamJohnson@gmail.com',
        progress: 75,
        percentage: '75%',
        passFail: 'Non',
        attendance: 5,
        image: '/assets/img/instructor.png',
        days: [
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '11',
        name: 'Emma Davis',
        email: 'EmmaDavis@gmail.com',
        progress: 70,
        percentage: '70%',
        passFail: 'Non',
        attendance: 5,
        image: '/assets/img/instructor.png',
        days: [
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '12',
        name: 'Noah Martinez',
        email: 'NoahMartinez@gmail.com',
        progress: 60,
        percentage: '60%',
        passFail: 'Non',
        attendance: 5,
        image: '/assets/img/instructor.png',
        days: [
          'passed',
          'passed',
          'not passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '13',
        name: 'Olivia Wilson',
        email: 'OliviaWilson@gmail.com',
        progress: 85,
        percentage: '85%',
        passFail: 'Non',
        attendance: 5,
        image: '/assets/img/instructor.png',
        days: [
          'passed',
          'passed',
          'passed',
          'passed',
          'not passed',
        ],
      },
      {
        id: '14',
        name: 'William Taylor',
        email: 'WilliamTaylor@gmail.com',
        progress: 80,
        percentage: '80%',
        passFail: 'Non',
        attendance: 5,
        image: '/assets/img/instructor.png',
        days: [
          'passed',
          'passed',
          'passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '15',
        name: 'Ava Anderson',
        email: 'AvaAnderson@gmail.com',
        progress: 90,
        percentage: '90%',
        passFail: 'Non',
        attendance: 5,
        image: '/assets/img/instructor.png',
        days: [
          'passed',
          'passed',
          'passed',
          'passed',
          'not passed',
        ],
      },
      {
        id: '16',
        name: 'James Walker',
        email: 'JamesWalker@gmail.com',
        progress: 75,
        percentage: '75%',
        passFail: 'Non',
        attendance: 5,
        image: '/assets/img/instructor.png',
        days: [
          'passed',
          'passed',
          'not passed',
          'not passed',
          'not passed',
        ],
      },
      {
        id: '17',
        name: 'Sophia Turner',
        email: 'SophiaTurner@gmail.com',
        progress: 95,
        percentage: '95%',
        passFail: 'Non',
        attendance: 5,
        image: '/assets/img/instructor.png',
        days: [
          'passed',
          'passed',
          'passed',
          'passed',
          'not passed',
        ],
      }
      
]

